#!/bin/sh
# builds the pindel file, using the htslib directory as an argument
# script adapted by Eric-Wubbo Lameijer, e.m.w.lameijer@gmail.com, based on http://www.kingcomputerservices.com/unix_101/tips_on_good_shell_programming_practices.htm

#  test if we have a argument on the command line

#if [ "$#" != "1" ]; then
 #   echo " "
  #  echo "INSTALL"
   # echo "    purpose:  builds the pindel executable "
    #echo "    IMPORTANT:  you should first clone and make/install htslib before installing Pindel. "
    #echo "    usage:    ./INSTALL [htslibdirectory]"
    #echo "    example:  ./INSTALL /home/user/tools/htslib/"
    #echo " "
    #exit 1
#fi

# we are ok at this point so continue processing here

# to make sure, convert relative path to absolute path

cd ./htslib
make
cd ../

ABSPATH=`cd ./htslib; pwd`

ABSPATH="$ABSPATH/"
echo "path is now: $ABSPATH"
if [ -e "Makefile.local" ];
  then LATERRUN="1";
fi 

make HTSLIB=$ABSPATH

if [ "$LATERRUN" != "1" ]; then
   echo "If this is the first time you're running this install script please wait a moment as we create the Makefile.local"
   sleep 10
   make HTSLIB=$ABSPATH
fi

if [ "$?" -ne 0 ]; then 
    echo "  "
    echo "INSTALL failed" 
    echo "Possible reasons: "
    echo "1. 'cannot cd to [path]"
    echo "->the htslib path provided was incorrect"
    echo " "
    echo "2. 'cannot find -lbam'"
    echo "->htslib was not properly compiled/made, in that case, go to the htslib directory and follow the htslib installation instructions"
    echo "and run 'make'."
    echo " "
    echo "For further help, see the FAQ file included in this directory"
    echo "Or contact us on kaiye@xjtu.edu.cn" 
    exit 1
else
    echo "  "
    mv src/pindel .
    mv src/pindel2vcf .
    mv src/sam2pindel .
    mv src/pindel2vcf4tcga .
    echo " "
    echo "Pindel successfully compiled. The pindel executable can be found in this directory."
    echo " "
    echo "You can test pindel with the example files in the demo directory; example commands are given in the RUNME in that directory."
    echo " " 
    echo "For help and background information, see the pindel wiki and its FAQ on gmt.genome.wustl.edu/packages/pindel, as well as"
    echo "the FAQ file in the Pindel root directory (the same directory as this INSTALL script is located)"
    echo "or contact us on kaiye@xjtu.edu.cn" 
    echo " "
fi 
